---
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    show-sql: true
    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/citizen
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

---
service-fine:
  base-url: http://localhost:8080