---
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:posgresql://localhost:5432/citizen
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

---
service-fine:
  base-url: http://localhost:8080/